# language used
language: android

# jkd version
jdk: oraclejdk8

# global variables used in this file
env:
  global:
    # target of development
    - ANDROID_TARGET=android-23
    # emulator version
    - ANDROID_ABI=armeabi-v7a
    # android version
    - ANDROID_VERSION=23
    # android tools used
    - ANDROID_BUILD_TOOLS=build-tools-23.0.3
    # Timeout for ADB
    - ADB_INSTALL_TIMEOUT=8

# components used to build
android:
  components:
  - extra-android-m2repository
  - extra-android-support
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - sys-img-armeabi-v7a-android-23
  - sys-img-x86-android-23

# to give execute permission
before_script:
  - chmod 777 gradlew
  - rm -r $HOME//app/src/androidTest/java/com/leaf/clips

# for caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  # unit testing
  - ./gradlew test
  # starting the emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
  # instrumental test
  - ./gradlew connectedCheck

after_success:
  - echo "oh fischi"
